//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationMergeTool.PresentationLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationMergeTool.PresentationLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version.
        /// </summary>
        public static string AppVersionTemplate {
            get {
                return ResourceManager.GetString("AppVersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge presentations.
        /// </summary>
        public static string Btn_MergePresentations {
            get {
                return ResourceManager.GetString("Btn_MergePresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string DataGridColumn_FileName {
            get {
                return ResourceManager.GetString("DataGridColumn_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path.
        /// </summary>
        public static string DataGridColumn_FullPath {
            get {
                return ResourceManager.GetString("DataGridColumn_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop your presentation files or folders containing them here. Subfolders are included automatically..
        /// </summary>
        public static string DragNDropAreaText {
            get {
                return ResourceManager.GetString("DragNDropAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Expander_HelpSection_Title {
            get {
                return ResourceManager.GetString("Expander_HelpSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export done!.
        /// </summary>
        public static string Export_Successful {
            get {
                return ResourceManager.GetString("Export_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string GroupBox_Controls {
            get {
                return ResourceManager.GetString("GroupBox_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an item by selecting it and pressing DELETE.
        /// </summary>
        public static string HelpElement_HowRemoveItem {
            get {
                return ResourceManager.GetString("HelpElement_HowRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag-and-drop the item to reorder.
        /// </summary>
        public static string HelpSection_ReorderItem {
            get {
                return ResourceManager.GetString("HelpSection_ReorderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation file (*.pptx)|*.pptx.
        /// </summary>
        public static string SaveAs_ExtensionFilter {
            get {
                return ResourceManager.GetString("SaveAs_ExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should NOT use your keyboard or mouse while the presentations are merged. Agreed?.
        /// </summary>
        public static string Warning_DoNotUseKeyboardOrMouse {
            get {
                return ResourceManager.GetString("Warning_DoNotUseKeyboardOrMouse", resourceCulture);
            }
        }
    }
}
